spring.application.name=review-service
server.port=8082

spring.datasource.url=jdbc:sqlite:review-service.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

movie-service.base-url=${MOVIE_SERVICE_URL:http://localhost:8081}